// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvkCO6GfsklsK7P0V0JZ3mtSghc-Xh0M',
    appId: '1:261507685114:web:176e8b9f793968fb8ac743',
    messagingSenderId: '261507685114',
    projectId: 'flashreview-26d02',
    authDomain: 'flashreview-26d02.firebaseapp.com',
    storageBucket: 'flashreview-26d02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvuCpDKICqCl4xYcq2aTrAJd_3bYImHxM',
    appId: '1:261507685114:android:3a60fbe782e06e908ac743',
    messagingSenderId: '261507685114',
    projectId: 'flashreview-26d02',
    storageBucket: 'flashreview-26d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnAEGL8zajQhvoZ6iWwpVMl_O0tcTJyk',
    appId: '1:261507685114:ios:6b8ca5f96168308c8ac743',
    messagingSenderId: '261507685114',
    projectId: 'flashreview-26d02',
    storageBucket: 'flashreview-26d02.firebasestorage.app',
    iosBundleId: 'com.example.flashRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnAEGL8zajQhvoZ6iWwpVMl_O0tcTJyk',
    appId: '1:261507685114:ios:57c81292163da65e8ac743',
    messagingSenderId: '261507685114',
    projectId: 'flashreview-26d02',
    storageBucket: 'flashreview-26d02.firebasestorage.app',
    iosBundleId: 'com.example.ankiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbvkCO6GfsklsK7P0V0JZ3mtSghc-Xh0M',
    appId: '1:261507685114:web:b1a92f8f4f5f0bf98ac743',
    messagingSenderId: '261507685114',
    projectId: 'flashreview-26d02',
    authDomain: 'flashreview-26d02.firebaseapp.com',
    storageBucket: 'flashreview-26d02.firebasestorage.app',
  );
}
